USE [IS495DB]
GO
/****** Object:  Table [dbo].[ASSIGNEE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ASSIGNEE](
	[AssignmentID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[WorkOrderID] [int] NOT NULL,
 CONSTRAINT [ASSIGNEE_PK] PRIMARY KEY CLUSTERED 
(
	[AssignmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BILLINGTYPE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BILLINGTYPE](
	[BillingTypeID] [int] NOT NULL,
	[BillingType] [varchar](100) NOT NULL,
 CONSTRAINT [BILLINGTYPE_PK] PRIMARY KEY CLUSTERED 
(
	[BillingTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPANY]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPANY](
	[CompanyID] [int] NOT NULL,
	[CompanyName] [varchar](100) NOT NULL,
 CONSTRAINT [COMPANY_PK] PRIMARY KEY CLUSTERED 
(
	[CompanyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTACT]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTACT](
	[ContactID] [int] NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](30) NULL,
	[EmailAddress] [varchar](70) NULL,
	[PhoneNumber] [varchar](15) NULL,
 CONSTRAINT [NewTable_PK] PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[CustomerID] [int] NOT NULL,
	[FirstName] [nchar](10) NULL,
	[LastName] [nchar](10) NULL,
	[DepartmentID] [int] NULL,
	[EmailAddress] [nchar](10) NULL,
	[PhoneNumber] [nchar](10) NULL,
	[Address] [nchar](10) NULL,
	[City] [nchar](10) NULL,
	[State/Province] [nchar](10) NULL,
	[Zipcode] [int] NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[DeaprtmentID] [int] NOT NULL,
	[CompanyName] [varchar](100) NOT NULL,
	[CompanyID] [int] NOT NULL,
 CONSTRAINT [DEPARTMENT_PK] PRIMARY KEY CLUSTERED 
(
	[DeaprtmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EmployeeID] [int] NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[DepartmentID] [int] NOT NULL,
	[EmailAddress] [varchar](70) NOT NULL,
	[JobTitleID] [int] NOT NULL,
	[PhoneNumber] [varchar](100) NOT NULL,
	[Address] [varchar](100) NOT NULL,
	[City] [varchar](100) NOT NULL,
	[State/Province] [varchar](100) NOT NULL,
	[ZipCode] [int] NOT NULL,
	[EmployeeTypeID] [int] NOT NULL,
	[UserName] [varchar](100) NULL,
	[Password] [varchar](100) NOT NULL,
 CONSTRAINT [EMPLOYEE_PK] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEETYPE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEETYPE](
	[EmployeeTypeID] [int] NOT NULL,
 CONSTRAINT [EMPLOYEETYPE_PK] PRIMARY KEY CLUSTERED 
(
	[EmployeeTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ENTRYTYPE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENTRYTYPE](
	[EntryTypeID] [int] NOT NULL,
	[EntryType] [varchar](100) NOT NULL,
	[Billable] [bit] NOT NULL,
 CONSTRAINT [ENTRYTYPE_PK] PRIMARY KEY CLUSTERED 
(
	[EntryTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GRANT]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GRANT](
	[GrantID] [int] NOT NULL,
	[GrantName] [varchar](100) NOT NULL,
	[Budget] [money] NOT NULL,
 CONSTRAINT [GRANT_PK] PRIMARY KEY CLUSTERED 
(
	[GrantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IPO]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IPO](
	[IPOID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[IPODate] [date] NOT NULL,
	[CreationDate] [date] NOT NULL,
	[IPOStatus_ID] [int] NOT NULL,
	[PaymentDate] [date] NOT NULL,
	[PaymentAmount] [money] NOT NULL,
	[TimeSheetID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IPOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IPORATE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IPORATE](
	[IPORateID] [int] NOT NULL,
	[ServiceRateID] [int] NULL,
	[IPOID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IPORateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IPOSTATUS]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IPOSTATUS](
	[IPOStatusID] [int] NOT NULL,
	[Status] [varchar](100) NOT NULL,
 CONSTRAINT [IPOSTATUS_PK] PRIMARY KEY CLUSTERED 
(
	[IPOStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOBTITLE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOBTITLE](
	[JobTitleID] [int] NOT NULL,
 CONSTRAINT [JOBTITLE_PK] PRIMARY KEY CLUSTERED 
(
	[JobTitleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRIORITY]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRIORITY](
	[ProrityID] [int] NOT NULL,
	[ProrityType] [varchar](100) NOT NULL,
 CONSTRAINT [PRIORITY_PK] PRIMARY KEY CLUSTERED 
(
	[ProrityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICERATE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICERATE](
	[ServiceRateID] [int] NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[FiscalYear] [int] NOT NULL,
	[Rate] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ServiceRateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICETYPE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICETYPE](
	[ServieTypeID] [int] NOT NULL,
	[ServiceType] [nchar](10) NULL,
	[Description] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ServieTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATUS]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATUS](
	[StatusID] [int] NOT NULL,
	[StatusType] [varchar](100) NOT NULL,
 CONSTRAINT [STATUS_PK] PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[test_table]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[test_table](
	[personID] [int] NULL,
	[FirstName] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIMESHEET]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIMESHEET](
	[TimeSheetID] [int] NOT NULL,
	[WorkOrderID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[BillingTypeID] [int] NOT NULL,
	[TimeTypeID] [int] NOT NULL,
	[ServiceTypeID] [int] NOT NULL,
	[IPOID] [int] NOT NULL,
	[DateTime] [date] NOT NULL,
	[TimeWorked] [float] NOT NULL,
	[WorkPerformed] [nchar](10) NOT NULL,
	[EntryTypeID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TimeSheetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIMETYPE]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIMETYPE](
	[TimeTypeID] [int] NOT NULL,
	[TimeType] [varchar](100) NOT NULL,
	[Category] [varchar](100) NOT NULL,
 CONSTRAINT [TIMETYPE_PK] PRIMARY KEY CLUSTERED 
(
	[TimeTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WO_CONTACT]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WO_CONTACT](
	[WO_ContactID] [int] NOT NULL,
	[ContactID] [int] NULL,
	[WorkOrderID] [int] NULL,
 CONSTRAINT [WO_CONTACT_PK] PRIMARY KEY CLUSTERED 
(
	[WO_ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WORKORDER]    Script Date: 10/13/2022 10:28:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORKORDER](
	[WorkOrderID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
	[PriorityID] [int] NOT NULL,
	[StatusID] [int] NOT NULL,
	[SubmittedDate] [date] NOT NULL,
	[Description] [varchar](100) NOT NULL,
	[StartDate] [date] NOT NULL,
	[DueDate] [date] NOT NULL,
	[CloseDate] [date] NOT NULL,
	[Notes] [varchar](100) NULL,
	[GrantID] [int] NOT NULL,
	[ProjectName] [varchar](100) NOT NULL,
 CONSTRAINT [WORKORDER_PK] PRIMARY KEY CLUSTERED 
(
	[WorkOrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASSIGNEE]  WITH CHECK ADD  CONSTRAINT [FK_ASSIGNEE_EMPLOYEE] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeID])
GO
ALTER TABLE [dbo].[ASSIGNEE] CHECK CONSTRAINT [FK_ASSIGNEE_EMPLOYEE]
GO
ALTER TABLE [dbo].[ASSIGNEE]  WITH CHECK ADD  CONSTRAINT [FK_ASSIGNEE_WORKORDER] FOREIGN KEY([WorkOrderID])
REFERENCES [dbo].[WORKORDER] ([WorkOrderID])
GO
ALTER TABLE [dbo].[ASSIGNEE] CHECK CONSTRAINT [FK_ASSIGNEE_WORKORDER]
GO
ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_DEPARTMENT] FOREIGN KEY([DepartmentID])
REFERENCES [dbo].[DEPARTMENT] ([DeaprtmentID])
GO
ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_DEPARTMENT]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTMENT_COMPANY] FOREIGN KEY([CompanyID])
REFERENCES [dbo].[COMPANY] ([CompanyID])
GO
ALTER TABLE [dbo].[DEPARTMENT] CHECK CONSTRAINT [FK_DEPARTMENT_COMPANY]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_DEPARTMENT] FOREIGN KEY([DepartmentID])
REFERENCES [dbo].[DEPARTMENT] ([DeaprtmentID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_DEPARTMENT]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_EMPLOYEETYPE] FOREIGN KEY([EmployeeTypeID])
REFERENCES [dbo].[EMPLOYEETYPE] ([EmployeeTypeID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_EMPLOYEETYPE]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_JOBTITLE] FOREIGN KEY([JobTitleID])
REFERENCES [dbo].[JOBTITLE] ([JobTitleID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_JOBTITLE]
GO
ALTER TABLE [dbo].[IPO]  WITH CHECK ADD  CONSTRAINT [FK_IPO_EMPLOYEE] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeID])
GO
ALTER TABLE [dbo].[IPO] CHECK CONSTRAINT [FK_IPO_EMPLOYEE]
GO
ALTER TABLE [dbo].[IPO]  WITH CHECK ADD  CONSTRAINT [FK_IPO_IPOSTATUS] FOREIGN KEY([IPOStatus_ID])
REFERENCES [dbo].[IPOSTATUS] ([IPOStatusID])
GO
ALTER TABLE [dbo].[IPO] CHECK CONSTRAINT [FK_IPO_IPOSTATUS]
GO
ALTER TABLE [dbo].[IPO]  WITH CHECK ADD  CONSTRAINT [FK_IPO_TIMESHEET] FOREIGN KEY([TimeSheetID])
REFERENCES [dbo].[TIMESHEET] ([TimeSheetID])
GO
ALTER TABLE [dbo].[IPO] CHECK CONSTRAINT [FK_IPO_TIMESHEET]
GO
ALTER TABLE [dbo].[IPORATE]  WITH CHECK ADD  CONSTRAINT [FK_IPORATE_IPO] FOREIGN KEY([IPOID])
REFERENCES [dbo].[IPO] ([IPOID])
GO
ALTER TABLE [dbo].[IPORATE] CHECK CONSTRAINT [FK_IPORATE_IPO]
GO
ALTER TABLE [dbo].[IPORATE]  WITH CHECK ADD  CONSTRAINT [FK_IPORATE_SERVICERATE] FOREIGN KEY([ServiceRateID])
REFERENCES [dbo].[SERVICERATE] ([ServiceRateID])
GO
ALTER TABLE [dbo].[IPORATE] CHECK CONSTRAINT [FK_IPORATE_SERVICERATE]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_BILLINGTYPE] FOREIGN KEY([BillingTypeID])
REFERENCES [dbo].[BILLINGTYPE] ([BillingTypeID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_BILLINGTYPE]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_EMPLOYEE] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_EMPLOYEE]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_ENTRYTYPE] FOREIGN KEY([EntryTypeID])
REFERENCES [dbo].[ENTRYTYPE] ([EntryTypeID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_ENTRYTYPE]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_IPO] FOREIGN KEY([IPOID])
REFERENCES [dbo].[IPO] ([IPOID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_IPO]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_SERVICETYPE] FOREIGN KEY([ServiceTypeID])
REFERENCES [dbo].[SERVICETYPE] ([ServieTypeID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_SERVICETYPE]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_TIMETYPE] FOREIGN KEY([TimeTypeID])
REFERENCES [dbo].[TIMETYPE] ([TimeTypeID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_TIMETYPE]
GO
ALTER TABLE [dbo].[TIMESHEET]  WITH CHECK ADD  CONSTRAINT [FK_TIMESHEET_WORKORDER] FOREIGN KEY([WorkOrderID])
REFERENCES [dbo].[WORKORDER] ([WorkOrderID])
GO
ALTER TABLE [dbo].[TIMESHEET] CHECK CONSTRAINT [FK_TIMESHEET_WORKORDER]
GO
ALTER TABLE [dbo].[WO_CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_WO_CONTACT_CONTACT] FOREIGN KEY([ContactID])
REFERENCES [dbo].[CONTACT] ([ContactID])
GO
ALTER TABLE [dbo].[WO_CONTACT] CHECK CONSTRAINT [FK_WO_CONTACT_CONTACT]
GO
ALTER TABLE [dbo].[WO_CONTACT]  WITH CHECK ADD  CONSTRAINT [FK_WO_CONTACT_WORKORDER] FOREIGN KEY([WorkOrderID])
REFERENCES [dbo].[WORKORDER] ([WorkOrderID])
GO
ALTER TABLE [dbo].[WO_CONTACT] CHECK CONSTRAINT [FK_WO_CONTACT_WORKORDER]
GO
ALTER TABLE [dbo].[WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_WORKORDER_CUSTOMER] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[CUSTOMER] ([CustomerID])
GO
ALTER TABLE [dbo].[WORKORDER] CHECK CONSTRAINT [FK_WORKORDER_CUSTOMER]
GO
ALTER TABLE [dbo].[WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_WORKORDER_EMPLOYEE] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeID])
GO
ALTER TABLE [dbo].[WORKORDER] CHECK CONSTRAINT [FK_WORKORDER_EMPLOYEE]
GO
ALTER TABLE [dbo].[WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_WORKORDER_GRANT] FOREIGN KEY([GrantID])
REFERENCES [dbo].[GRANT] ([GrantID])
GO
ALTER TABLE [dbo].[WORKORDER] CHECK CONSTRAINT [FK_WORKORDER_GRANT]
GO
ALTER TABLE [dbo].[WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_WORKORDER_PRIORITY] FOREIGN KEY([PriorityID])
REFERENCES [dbo].[PRIORITY] ([ProrityID])
GO
ALTER TABLE [dbo].[WORKORDER] CHECK CONSTRAINT [FK_WORKORDER_PRIORITY]
GO
ALTER TABLE [dbo].[WORKORDER]  WITH CHECK ADD  CONSTRAINT [FK_WORKORDER_STATUS] FOREIGN KEY([StatusID])
REFERENCES [dbo].[STATUS] ([StatusID])
GO
ALTER TABLE [dbo].[WORKORDER] CHECK CONSTRAINT [FK_WORKORDER_STATUS]
GO
