#!/usr/bin/bash
sequelize seed:generate --name initial-serviceratetype
sequelize seed:generate --name initial-billingtype
sequelize seed:generate --name initial-timesheet
sequelize seed:generate --name initial-workorder
sequelize seed:generate --name initial-servicerate
sequelize seed:generate --name initial-iporate
sequelize seed:generate --name initial-jobtitle
sequelize seed:generate --name initial-contact
sequelize seed:generate --name initial-grant
sequelize seed:generate --name initial-entrytype
sequelize seed:generate --name initial-company
sequelize seed:generate --name initial-assignee
sequelize seed:generate --name initial-department
sequelize seed:generate --name initial-customer
sequelize seed:generate --name initial-workorderpriority
sequelize seed:generate --name initial-employeetype
sequelize seed:generate --name initial-ipostatus
sequelize seed:generate --name initial-ipo
sequelize seed:generate --name initial-workorderstatus
sequelize seed:generate --name initial-workordergrant
sequelize seed:generate --name initial-employee
